(sleep 5 && ./rasp-fan) &
(sleep 10 && /rasp-fan) &
(sleep 15 && /rasp-fan) &
(sleep 20 && /rasp-fan) &
(sleep 25 && /rasp-fan) &
(sleep 30 && /rasp-fan) &
(sleep 35 && /rasp-fan) &
(sleep 40 && /rasp-fan) &
(sleep 45 && /rasp-fan) &
(sleep 50 && /rasp-fan) &
(sleep 55 && /rasp-fan) &
(sleep 60 && /rasp-fan) &